[package]
name = "schluesselwert"
version = "0.1.0"
authors = ["Bastian Köcher <git@kchr.de>"]

[dependencies]
raft = "0.3.1"
rocksdb = "0.10.1"
tokio = "0.1.7"
failure = "0.1.1"
byteorder = "1.2.3"
protobuf = "2.0.4"
